# Generated by Django 3.1 on 2020-12-03 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organism',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('edibility', models.BooleanField(blank=True, null=True)),
                ('ecosystem', models.CharField(blank=True, choices=[('Temperate Rainforest', 'Temperate Rainforest'), ('Tropical Rainforest', 'Tropical Rainforest'), ('DESERT', 'Desert'), ('Grassland', 'Grassland'), ('Taiga', 'Taiga'), ('Tundra', 'Tundra'), ('Chaparral', 'Chaparral'), ('Ocean', 'Ocean')], max_length=255, null=True)),
            ],
        ),
    ]
