# Generated by Django 3.1 on 2020-12-03 02:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('natureShareApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organism',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='organism',
            name='weather',
            field=models.CharField(blank=True, choices=[('Sunny', 'Sunny'), ('Cloudy', 'Cloudy'), ('Rainy', 'Rainy'), ('Windy', 'Windy'), ('Snowy', 'Snowy'), ('Other', 'Other')], max_length=255, null=True),
        ),
    ]
