# Generated by Django 3.1.4 on 2020-12-09 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('natureShareApp', '0004_auto_20201203_0449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organism',
            name='ecosystem',
            field=models.CharField(blank=True, choices=[('Temperate Rainforest', 'Temperate Rainforest'), ('Tropical Rainforest', 'Tropical Rainforest'), ('Desert', 'Desert'), ('Grassland', 'Grassland'), ('Taiga', 'Taiga'), ('Tundra', 'Tundra'), ('Chaparral', 'Chaparral'), ('Ocean', 'Ocean'), ('Unknown', 'Unknown'), ('Other', 'Other')], max_length=255, null=True),
        ),
    ]
