# Generated by Django 3.1.4 on 2020-12-09 04:36

from django.db import migrations
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('natureShareApp', '0005_auto_20201209_0348'),
    ]

    operations = [
        migrations.AddField(
            model_name='organism',
            name='location',
            field=location_field.models.plain.PlainLocationField(blank=True, max_length=63, null=True),
        ),
    ]
