# Generated by Django 3.1.4 on 2020-12-10 05:26

from django.db import migrations
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('natureShareApp', '0006_organism_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organism',
            name='location',
            field=location_field.models.plain.PlainLocationField(blank=True, default='45.502978246693786,-122.67608642578126', max_length=63, null=True),
        ),
    ]
